TRUNCATE TABLE ExchangeOrders
DELETE FROM Orders
DBCC CHECKIDENT ('Orders', RESEED, 0)

TRUNCATE TABLE Logs

TRUNCATE TABLE QuoteAssets
TRUNCATE TABLE Keys
DELETE FROM Users
DBCC CHECKIDENT ('Users', RESEED, 0)
